apply plugin: 'com.android.application'

android {
    namespace = "com.beiko.smsforwarder"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.beiko.smsforwarder"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion 28
        versionCode 9
        versionName "1.1.6"
    }

    signingConfigs {
        release {
            storeFile file("${System.properties['user.home']}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
