apply plugin: 'com.android.application'

android {
    namespace = "com.beiko.smsforwarder"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.beiko.smsforwarder"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("${System.properties['user.home']}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
