plugins {
    id 'com.android.application'
}

android {
    namespace 'com.beiko.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'com.beiko.mobile'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.11.0'
}
